#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLHS
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QUANLYHOSO")]
	public partial class LINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertDuAn(DuAn instance);
    partial void UpdateDuAn(DuAn instance);
    partial void DeleteDuAn(DuAn instance);
    #endregion
		
		public LINQDataContext() : 
				base(global::QLHS.Properties.Settings.Default.QUANLYHOSOConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien_DuAn> NhanVien_DuAns
		{
			get
			{
				return this.GetTable<NhanVien_DuAn>();
			}
		}
		
		public System.Data.Linq.Table<DuAn> DuAns
		{
			get
			{
				return this.GetTable<DuAn>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_capbac", IsComposable=true)]
		public string lay_capbac([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> manhanvien)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manhanvien).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_chucvu", IsComposable=true)]
		public string lay_chucvu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> manhanvien)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manhanvien).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_cottenduan", IsComposable=true)]
		public IQueryable<lay_cottenduanResult> lay_cottenduan()
		{
			return this.CreateMethodCallQuery<lay_cottenduanResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_cottennhanvien", IsComposable=true)]
		public IQueryable<lay_cottennhanvienResult> lay_cottennhanvien()
		{
			return this.CreateMethodCallQuery<lay_cottennhanvienResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_diadiem", IsComposable=true)]
		public string lay_diadiem([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_dientich", IsComposable=true)]
		public string lay_dientich([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_filedinhkiem", IsComposable=true)]
		public string lay_filedinhkiem([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_giatrihopdong", IsComposable=true)]
		public System.Nullable<double> lay_giatrihopdong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((System.Nullable<double>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_giatrithanhquyettoan", IsComposable=true)]
		public System.Nullable<double> lay_giatrithanhquyettoan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((System.Nullable<double>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_madoitruong", IsComposable=true)]
		public System.Nullable<int> lay_madoitruong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_manguoilaphoso", IsComposable=true)]
		public System.Nullable<int> lay_manguoilaphoso([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_ngaybatdau", IsComposable=true)]
		public string lay_ngaybatdau([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_ngayketthuc", IsComposable=true)]
		public string lay_ngayketthuc([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_tenduan", IsComposable=true)]
		public string lay_tenduan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_tennhanvien", IsComposable=true)]
		public string lay_tennhanvien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> manhanvien)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manhanvien).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_trangthai", IsComposable=true)]
		public System.Nullable<int> lay_trangthai([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> manhanvien)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manhanvien).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_idcuoi", IsComposable=true)]
		public System.Nullable<int> lay_idcuoi()
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.chuyensx", IsComposable=true)]
		public IQueryable<chuyensxResult> chuyensx()
		{
			return this.CreateMethodCallQuery<chuyensxResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_cottenchuyengia", IsComposable=true)]
		public IQueryable<lay_cottenchuyengiaResult> lay_cottenchuyengia()
		{
			return this.CreateMethodCallQuery<lay_cottenchuyengiaResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.nlay_manhanvien", IsComposable=true)]
		public System.Nullable<int> nlay_manhanvien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string tennhanvien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> loai)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tennhanvien, loai).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_idcuoinhanvien", IsComposable=true)]
		public System.Nullable<int> lay_idcuoinhanvien()
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.timkiem_nam", IsComposable=true)]
		public IQueryable<timkiem_namResult> timkiem_nam([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nam)
		{
			return this.CreateMethodCallQuery<timkiem_namResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nam);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.timkiem_tenduan", IsComposable=true)]
		public IQueryable<timkiem_tenduanResult> timkiem_tenduan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string ten)
		{
			return this.CreateMethodCallQuery<timkiem_tenduanResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ten);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ntimkiemchung", IsComposable=true)]
		public IQueryable<ntimkiemchungResult> ntimkiemchung([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string chuoi)
		{
			return this.CreateMethodCallQuery<ntimkiemchungResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), chuoi);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.nthem_nhanvien")]
		public int nthem_nhanvien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string tennhanvien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string capbac, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string chucvu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> trangthai, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(2000)")] string ghichu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tennhanvien, capbac, chucvu, trangthai, ghichu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.nsua_nhanvien")]
		public int nsua_nhanvien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> manhanvien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string tennhanvien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string capbac, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string chucvu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> trangthai, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(2000)")] string ghichu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manhanvien, tennhanvien, capbac, chucvu, trangthai, ghichu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.nlay_bangnhanvien", IsComposable=true)]
		public IQueryable<nlay_bangnhanvienResult> nlay_bangnhanvien()
		{
			return this.CreateMethodCallQuery<nlay_bangnhanvienResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.xoaduan")]
		public int xoaduan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.xoanhanvien")]
		public int xoanhanvien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> ma)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.laybangchuyengia", IsComposable=true)]
		public IQueryable<laybangchuyengiaResult> laybangchuyengia()
		{
			return this.CreateMethodCallQuery<laybangchuyengiaResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.nlay_bangduan", IsComposable=true)]
		public IQueryable<nlay_bangduanResult> nlay_bangduan()
		{
			return this.CreateMethodCallQuery<nlay_bangduanResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_nlhskhac", IsComposable=true)]
		public string lay_nlhskhac([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_dttckhac", IsComposable=true)]
		public string lay_dttckhac([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_ghichuduan", IsComposable=true)]
		public string lay_ghichuduan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_ghichunhanvien", IsComposable=true)]
		public string lay_ghichunhanvien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> manhanvien)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manhanvien).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ntimkiem_nam", IsComposable=true)]
		public IQueryable<ntimkiem_namResult> ntimkiem_nam([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string nam)
		{
			return this.CreateMethodCallQuery<ntimkiem_namResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nam);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_manhanvien", IsComposable=true)]
		public System.Nullable<int> lay_manhanvien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string tennhanvien, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string capbac, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string chucvu)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tennhanvien, capbac, chucvu).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.nthem_duan")]
		public int nthem_duan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string tenduan, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string diadiem, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dientich, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ngaybatdau, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ngayketthuc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> gthd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> gttqt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nth, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> dttc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(2000)")] string file, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(2000)")] string ghichu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string nlhskhac, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string dttckhac, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string gthdchu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string gttqtchu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenduan, diadiem, dientich, ngaybatdau, ngayketthuc, gthd, gttqt, nth, dttc, file, ghichu, nlhskhac, dttckhac, gthdchu, gttqtchu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.nsua_duan")]
		public int nsua_duan(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string tenduan, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string diadiem, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dientich, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ngaybatdau, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string ngayketthuc, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> gthd, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Float")] System.Nullable<double> gttqt, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nth, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> dttc, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(2000)")] string file, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(2000)")] string ghichu, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string nlhskhac, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string dttckhac, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string gthdchu, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string gttqtchu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan, tenduan, diadiem, dientich, ngaybatdau, ngayketthuc, gthd, gttqt, nth, dttc, file, ghichu, nlhskhac, dttckhac, gthdchu, gttqtchu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_gthdchu", IsComposable=true)]
		public string lay_gthdchu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.lay_gttqtchu", IsComposable=true)]
		public string lay_gttqtchu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> maduan)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maduan).ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNhanVien;
		
		private string _TenNhanVien;
		
		private string _CapBacHienTai;
		
		private string _ChucVuHienTai;
		
		private System.Nullable<int> _TrangThai;
		
		private string _GhiChu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhanVienChanging(int value);
    partial void OnMaNhanVienChanged();
    partial void OnTenNhanVienChanging(string value);
    partial void OnTenNhanVienChanged();
    partial void OnCapBacHienTaiChanging(string value);
    partial void OnCapBacHienTaiChanged();
    partial void OnChucVuHienTaiChanging(string value);
    partial void OnChucVuHienTaiChanged();
    partial void OnTrangThaiChanging(System.Nullable<int> value);
    partial void OnTrangThaiChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public NhanVien()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhanVien", DbType="NVarChar(200)")]
		public string TenNhanVien
		{
			get
			{
				return this._TenNhanVien;
			}
			set
			{
				if ((this._TenNhanVien != value))
				{
					this.OnTenNhanVienChanging(value);
					this.SendPropertyChanging();
					this._TenNhanVien = value;
					this.SendPropertyChanged("TenNhanVien");
					this.OnTenNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapBacHienTai", DbType="NVarChar(200)")]
		public string CapBacHienTai
		{
			get
			{
				return this._CapBacHienTai;
			}
			set
			{
				if ((this._CapBacHienTai != value))
				{
					this.OnCapBacHienTaiChanging(value);
					this.SendPropertyChanging();
					this._CapBacHienTai = value;
					this.SendPropertyChanged("CapBacHienTai");
					this.OnCapBacHienTaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVuHienTai", DbType="NVarChar(200)")]
		public string ChucVuHienTai
		{
			get
			{
				return this._ChucVuHienTai;
			}
			set
			{
				if ((this._ChucVuHienTai != value))
				{
					this.OnChucVuHienTaiChanging(value);
					this.SendPropertyChanging();
					this._ChucVuHienTai = value;
					this.SendPropertyChanged("ChucVuHienTai");
					this.OnChucVuHienTaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Int")]
		public System.Nullable<int> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(2000)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien_DuAn")]
	public partial class NhanVien_DuAn
	{
		
		private int _MaNhanVien;
		
		private int _MaDuAn;
		
		private string _CapBac;
		
		private string _ChucVu;
		
		public NhanVien_DuAn()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="Int NOT NULL")]
		public int MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this._MaNhanVien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDuAn", DbType="Int NOT NULL")]
		public int MaDuAn
		{
			get
			{
				return this._MaDuAn;
			}
			set
			{
				if ((this._MaDuAn != value))
				{
					this._MaDuAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapBac", DbType="NVarChar(200)")]
		public string CapBac
		{
			get
			{
				return this._CapBac;
			}
			set
			{
				if ((this._CapBac != value))
				{
					this._CapBac = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NVarChar(200)")]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this._ChucVu = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DuAn")]
	public partial class DuAn : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaDuAn;
		
		private string _TenDuAn;
		
		private string _DiaDiem;
		
		private string _DienTich;
		
		private string _NgayBatDau;
		
		private string _NgayKetThuc;
		
		private System.Nullable<double> _GiaTriHopDong;
		
		private System.Nullable<double> _GiaTriThanhQuyetToan;
		
		private System.Nullable<int> _MaDoiTruong;
		
		private System.Nullable<int> _MaNguoiLapHoSo;
		
		private string _FileDinhKem;
		
		private string _GhiChu;
		
		private string _nlhskhac;
		
		private string _dttckhac;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDuAnChanging(int value);
    partial void OnMaDuAnChanged();
    partial void OnTenDuAnChanging(string value);
    partial void OnTenDuAnChanged();
    partial void OnDiaDiemChanging(string value);
    partial void OnDiaDiemChanged();
    partial void OnDienTichChanging(string value);
    partial void OnDienTichChanged();
    partial void OnNgayBatDauChanging(string value);
    partial void OnNgayBatDauChanged();
    partial void OnNgayKetThucChanging(string value);
    partial void OnNgayKetThucChanged();
    partial void OnGiaTriHopDongChanging(System.Nullable<double> value);
    partial void OnGiaTriHopDongChanged();
    partial void OnGiaTriThanhQuyetToanChanging(System.Nullable<double> value);
    partial void OnGiaTriThanhQuyetToanChanged();
    partial void OnMaDoiTruongChanging(System.Nullable<int> value);
    partial void OnMaDoiTruongChanged();
    partial void OnMaNguoiLapHoSoChanging(System.Nullable<int> value);
    partial void OnMaNguoiLapHoSoChanged();
    partial void OnFileDinhKemChanging(string value);
    partial void OnFileDinhKemChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnnlhskhacChanging(string value);
    partial void OnnlhskhacChanged();
    partial void OndttckhacChanging(string value);
    partial void OndttckhacChanged();
    #endregion
		
		public DuAn()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDuAn", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaDuAn
		{
			get
			{
				return this._MaDuAn;
			}
			set
			{
				if ((this._MaDuAn != value))
				{
					this.OnMaDuAnChanging(value);
					this.SendPropertyChanging();
					this._MaDuAn = value;
					this.SendPropertyChanged("MaDuAn");
					this.OnMaDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDuAn", DbType="NVarChar(200)")]
		public string TenDuAn
		{
			get
			{
				return this._TenDuAn;
			}
			set
			{
				if ((this._TenDuAn != value))
				{
					this.OnTenDuAnChanging(value);
					this.SendPropertyChanging();
					this._TenDuAn = value;
					this.SendPropertyChanged("TenDuAn");
					this.OnTenDuAnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="NVarChar(200)")]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this.OnDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._DiaDiem = value;
					this.SendPropertyChanged("DiaDiem");
					this.OnDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich", DbType="VarChar(50)")]
		public string DienTich
		{
			get
			{
				return this._DienTich;
			}
			set
			{
				if ((this._DienTich != value))
				{
					this.OnDienTichChanging(value);
					this.SendPropertyChanging();
					this._DienTich = value;
					this.SendPropertyChanged("DienTich");
					this.OnDienTichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="VarChar(10)")]
		public string NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this.OnNgayBatDauChanging(value);
					this.SendPropertyChanging();
					this._NgayBatDau = value;
					this.SendPropertyChanged("NgayBatDau");
					this.OnNgayBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="VarChar(10)")]
		public string NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this.OnNgayKetThucChanging(value);
					this.SendPropertyChanging();
					this._NgayKetThuc = value;
					this.SendPropertyChanged("NgayKetThuc");
					this.OnNgayKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriHopDong", DbType="Float")]
		public System.Nullable<double> GiaTriHopDong
		{
			get
			{
				return this._GiaTriHopDong;
			}
			set
			{
				if ((this._GiaTriHopDong != value))
				{
					this.OnGiaTriHopDongChanging(value);
					this.SendPropertyChanging();
					this._GiaTriHopDong = value;
					this.SendPropertyChanged("GiaTriHopDong");
					this.OnGiaTriHopDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriThanhQuyetToan", DbType="Float")]
		public System.Nullable<double> GiaTriThanhQuyetToan
		{
			get
			{
				return this._GiaTriThanhQuyetToan;
			}
			set
			{
				if ((this._GiaTriThanhQuyetToan != value))
				{
					this.OnGiaTriThanhQuyetToanChanging(value);
					this.SendPropertyChanging();
					this._GiaTriThanhQuyetToan = value;
					this.SendPropertyChanged("GiaTriThanhQuyetToan");
					this.OnGiaTriThanhQuyetToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDoiTruong", DbType="Int")]
		public System.Nullable<int> MaDoiTruong
		{
			get
			{
				return this._MaDoiTruong;
			}
			set
			{
				if ((this._MaDoiTruong != value))
				{
					this.OnMaDoiTruongChanging(value);
					this.SendPropertyChanging();
					this._MaDoiTruong = value;
					this.SendPropertyChanged("MaDoiTruong");
					this.OnMaDoiTruongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNguoiLapHoSo", DbType="Int")]
		public System.Nullable<int> MaNguoiLapHoSo
		{
			get
			{
				return this._MaNguoiLapHoSo;
			}
			set
			{
				if ((this._MaNguoiLapHoSo != value))
				{
					this.OnMaNguoiLapHoSoChanging(value);
					this.SendPropertyChanging();
					this._MaNguoiLapHoSo = value;
					this.SendPropertyChanged("MaNguoiLapHoSo");
					this.OnMaNguoiLapHoSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileDinhKem", DbType="NVarChar(2000)")]
		public string FileDinhKem
		{
			get
			{
				return this._FileDinhKem;
			}
			set
			{
				if ((this._FileDinhKem != value))
				{
					this.OnFileDinhKemChanging(value);
					this.SendPropertyChanging();
					this._FileDinhKem = value;
					this.SendPropertyChanged("FileDinhKem");
					this.OnFileDinhKemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(2000)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nlhskhac", DbType="NVarChar(500)")]
		public string nlhskhac
		{
			get
			{
				return this._nlhskhac;
			}
			set
			{
				if ((this._nlhskhac != value))
				{
					this.OnnlhskhacChanging(value);
					this.SendPropertyChanging();
					this._nlhskhac = value;
					this.SendPropertyChanged("nlhskhac");
					this.OnnlhskhacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dttckhac", DbType="NVarChar(500)")]
		public string dttckhac
		{
			get
			{
				return this._dttckhac;
			}
			set
			{
				if ((this._dttckhac != value))
				{
					this.OndttckhacChanging(value);
					this.SendPropertyChanging();
					this._dttckhac = value;
					this.SendPropertyChanged("dttckhac");
					this.OndttckhacChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class lay_cottenduanResult
	{
		
		private string _tenduan;
		
		public lay_cottenduanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenduan", DbType="NVarChar(200)")]
		public string tenduan
		{
			get
			{
				return this._tenduan;
			}
			set
			{
				if ((this._tenduan != value))
				{
					this._tenduan = value;
				}
			}
		}
	}
	
	public partial class lay_cottennhanvienResult
	{
		
		private string _tennhanvien;
		
		public lay_cottennhanvienResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennhanvien", DbType="NVarChar(200)")]
		public string tennhanvien
		{
			get
			{
				return this._tennhanvien;
			}
			set
			{
				if ((this._tennhanvien != value))
				{
					this._tennhanvien = value;
				}
			}
		}
	}
	
	public partial class chuyensxResult
	{
		
		private System.Nullable<int> _MaDuAn;
		
		private string _NgayBatDau;
		
		private string _NgayKetThuc;
		
		public chuyensxResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDuAn", DbType="Int")]
		public System.Nullable<int> MaDuAn
		{
			get
			{
				return this._MaDuAn;
			}
			set
			{
				if ((this._MaDuAn != value))
				{
					this._MaDuAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="VarChar(10)")]
		public string NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this._NgayBatDau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="VarChar(10)")]
		public string NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this._NgayKetThuc = value;
				}
			}
		}
	}
	
	public partial class lay_cottenchuyengiaResult
	{
		
		private string _tennhanvien;
		
		public lay_cottenchuyengiaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennhanvien", DbType="NVarChar(200)")]
		public string tennhanvien
		{
			get
			{
				return this._tennhanvien;
			}
			set
			{
				if ((this._tennhanvien != value))
				{
					this._tennhanvien = value;
				}
			}
		}
	}
	
	public partial class timkiem_namResult
	{
		
		private System.Nullable<int> _MaDuAn;
		
		private int _STT;
		
		private string _TenDuAn;
		
		private string _DiaDiem;
		
		private string _DienTich;
		
		private string _NgayBatDau;
		
		private string _NgayKetThuc;
		
		private System.Nullable<double> _GiaTriHopDong;
		
		private System.Nullable<double> _GiaTriThanhQuyetToan;
		
		private string _TenDoiTruong;
		
		private string _TenNguoiLapHoSo;
		
		private string _FileDinhKem;
		
		private string _GhiChu;
		
		public timkiem_namResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDuAn", DbType="Int")]
		public System.Nullable<int> MaDuAn
		{
			get
			{
				return this._MaDuAn;
			}
			set
			{
				if ((this._MaDuAn != value))
				{
					this._MaDuAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int NOT NULL")]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this._STT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDuAn", DbType="NVarChar(200)")]
		public string TenDuAn
		{
			get
			{
				return this._TenDuAn;
			}
			set
			{
				if ((this._TenDuAn != value))
				{
					this._TenDuAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="NVarChar(200)")]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this._DiaDiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich", DbType="VarChar(50)")]
		public string DienTich
		{
			get
			{
				return this._DienTich;
			}
			set
			{
				if ((this._DienTich != value))
				{
					this._DienTich = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="VarChar(10)")]
		public string NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this._NgayBatDau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="VarChar(10)")]
		public string NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this._NgayKetThuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriHopDong", DbType="Float")]
		public System.Nullable<double> GiaTriHopDong
		{
			get
			{
				return this._GiaTriHopDong;
			}
			set
			{
				if ((this._GiaTriHopDong != value))
				{
					this._GiaTriHopDong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriThanhQuyetToan", DbType="Float")]
		public System.Nullable<double> GiaTriThanhQuyetToan
		{
			get
			{
				return this._GiaTriThanhQuyetToan;
			}
			set
			{
				if ((this._GiaTriThanhQuyetToan != value))
				{
					this._GiaTriThanhQuyetToan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDoiTruong", DbType="NVarChar(200)")]
		public string TenDoiTruong
		{
			get
			{
				return this._TenDoiTruong;
			}
			set
			{
				if ((this._TenDoiTruong != value))
				{
					this._TenDoiTruong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiLapHoSo", DbType="NVarChar(200)")]
		public string TenNguoiLapHoSo
		{
			get
			{
				return this._TenNguoiLapHoSo;
			}
			set
			{
				if ((this._TenNguoiLapHoSo != value))
				{
					this._TenNguoiLapHoSo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileDinhKem", DbType="NVarChar(2000)")]
		public string FileDinhKem
		{
			get
			{
				return this._FileDinhKem;
			}
			set
			{
				if ((this._FileDinhKem != value))
				{
					this._FileDinhKem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(2000)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this._GhiChu = value;
				}
			}
		}
	}
	
	public partial class timkiem_tenduanResult
	{
		
		private System.Nullable<int> _MaDuAn;
		
		private int _STT;
		
		private string _TenDuAn;
		
		private string _DiaDiem;
		
		private string _DienTich;
		
		private string _NgayBatDau;
		
		private string _NgayKetThuc;
		
		private System.Nullable<double> _GiaTriHopDong;
		
		private System.Nullable<double> _GiaTriThanhQuyetToan;
		
		private string _TenDoiTruong;
		
		private string _TenNguoiLapHoSo;
		
		private string _FileDinhKem;
		
		private string _GhiChu;
		
		public timkiem_tenduanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDuAn", DbType="Int")]
		public System.Nullable<int> MaDuAn
		{
			get
			{
				return this._MaDuAn;
			}
			set
			{
				if ((this._MaDuAn != value))
				{
					this._MaDuAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int NOT NULL")]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this._STT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDuAn", DbType="NVarChar(200)")]
		public string TenDuAn
		{
			get
			{
				return this._TenDuAn;
			}
			set
			{
				if ((this._TenDuAn != value))
				{
					this._TenDuAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="NVarChar(200)")]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this._DiaDiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich", DbType="VarChar(50)")]
		public string DienTich
		{
			get
			{
				return this._DienTich;
			}
			set
			{
				if ((this._DienTich != value))
				{
					this._DienTich = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="VarChar(10)")]
		public string NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this._NgayBatDau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="VarChar(10)")]
		public string NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this._NgayKetThuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriHopDong", DbType="Float")]
		public System.Nullable<double> GiaTriHopDong
		{
			get
			{
				return this._GiaTriHopDong;
			}
			set
			{
				if ((this._GiaTriHopDong != value))
				{
					this._GiaTriHopDong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriThanhQuyetToan", DbType="Float")]
		public System.Nullable<double> GiaTriThanhQuyetToan
		{
			get
			{
				return this._GiaTriThanhQuyetToan;
			}
			set
			{
				if ((this._GiaTriThanhQuyetToan != value))
				{
					this._GiaTriThanhQuyetToan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDoiTruong", DbType="NVarChar(200)")]
		public string TenDoiTruong
		{
			get
			{
				return this._TenDoiTruong;
			}
			set
			{
				if ((this._TenDoiTruong != value))
				{
					this._TenDoiTruong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiLapHoSo", DbType="NVarChar(200)")]
		public string TenNguoiLapHoSo
		{
			get
			{
				return this._TenNguoiLapHoSo;
			}
			set
			{
				if ((this._TenNguoiLapHoSo != value))
				{
					this._TenNguoiLapHoSo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileDinhKem", DbType="NVarChar(2000)")]
		public string FileDinhKem
		{
			get
			{
				return this._FileDinhKem;
			}
			set
			{
				if ((this._FileDinhKem != value))
				{
					this._FileDinhKem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(2000)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this._GhiChu = value;
				}
			}
		}
	}
	
	public partial class ntimkiemchungResult
	{
		
		private System.Nullable<int> _MaDuAn;
		
		private int _STT;
		
		private string _TenDuAn;
		
		private string _DiaDiem;
		
		private string _DienTich;
		
		private string _NgayBatDau;
		
		private string _NgayKetThuc;
		
		private System.Nullable<double> _GiaTriHopDong;
		
		private System.Nullable<double> _GiaTriThanhQuyetToan;
		
		private string _TenDoiTruong;
		
		private string _TenNguoiLapHoSo;
		
		private string _FileDinhKem;
		
		private string _GhiChu;
		
		public ntimkiemchungResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDuAn", DbType="Int")]
		public System.Nullable<int> MaDuAn
		{
			get
			{
				return this._MaDuAn;
			}
			set
			{
				if ((this._MaDuAn != value))
				{
					this._MaDuAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", DbType="Int NOT NULL")]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this._STT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDuAn", DbType="NVarChar(200)")]
		public string TenDuAn
		{
			get
			{
				return this._TenDuAn;
			}
			set
			{
				if ((this._TenDuAn != value))
				{
					this._TenDuAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="NVarChar(200)")]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this._DiaDiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich", DbType="VarChar(50)")]
		public string DienTich
		{
			get
			{
				return this._DienTich;
			}
			set
			{
				if ((this._DienTich != value))
				{
					this._DienTich = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="VarChar(10)")]
		public string NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this._NgayBatDau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="VarChar(10)")]
		public string NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this._NgayKetThuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriHopDong", DbType="Float")]
		public System.Nullable<double> GiaTriHopDong
		{
			get
			{
				return this._GiaTriHopDong;
			}
			set
			{
				if ((this._GiaTriHopDong != value))
				{
					this._GiaTriHopDong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriThanhQuyetToan", DbType="Float")]
		public System.Nullable<double> GiaTriThanhQuyetToan
		{
			get
			{
				return this._GiaTriThanhQuyetToan;
			}
			set
			{
				if ((this._GiaTriThanhQuyetToan != value))
				{
					this._GiaTriThanhQuyetToan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDoiTruong", DbType="NVarChar(200)")]
		public string TenDoiTruong
		{
			get
			{
				return this._TenDoiTruong;
			}
			set
			{
				if ((this._TenDoiTruong != value))
				{
					this._TenDoiTruong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiLapHoSo", DbType="NVarChar(200)")]
		public string TenNguoiLapHoSo
		{
			get
			{
				return this._TenNguoiLapHoSo;
			}
			set
			{
				if ((this._TenNguoiLapHoSo != value))
				{
					this._TenNguoiLapHoSo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileDinhKem", DbType="NVarChar(2000)")]
		public string FileDinhKem
		{
			get
			{
				return this._FileDinhKem;
			}
			set
			{
				if ((this._FileDinhKem != value))
				{
					this._FileDinhKem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(2000)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this._GhiChu = value;
				}
			}
		}
	}
	
	public partial class nlay_bangnhanvienResult
	{
		
		private int _manhanvien;
		
		private string _tennhanvien;
		
		private string _CapBacHienTai;
		
		private string _ChucVuHienTai;
		
		private string _ghichu;
		
		public nlay_bangnhanvienResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manhanvien", DbType="Int NOT NULL")]
		public int manhanvien
		{
			get
			{
				return this._manhanvien;
			}
			set
			{
				if ((this._manhanvien != value))
				{
					this._manhanvien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennhanvien", DbType="NVarChar(200)")]
		public string tennhanvien
		{
			get
			{
				return this._tennhanvien;
			}
			set
			{
				if ((this._tennhanvien != value))
				{
					this._tennhanvien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapBacHienTai", DbType="NVarChar(200)")]
		public string CapBacHienTai
		{
			get
			{
				return this._CapBacHienTai;
			}
			set
			{
				if ((this._CapBacHienTai != value))
				{
					this._CapBacHienTai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVuHienTai", DbType="NVarChar(200)")]
		public string ChucVuHienTai
		{
			get
			{
				return this._ChucVuHienTai;
			}
			set
			{
				if ((this._ChucVuHienTai != value))
				{
					this._ChucVuHienTai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghichu", DbType="NVarChar(2000)")]
		public string ghichu
		{
			get
			{
				return this._ghichu;
			}
			set
			{
				if ((this._ghichu != value))
				{
					this._ghichu = value;
				}
			}
		}
	}
	
	public partial class laybangchuyengiaResult
	{
		
		private int _manhanvien;
		
		private string _tennhanvien;
		
		private string _CapBacHienTai;
		
		private string _ChucVuHienTai;
		
		private string _ghichu;
		
		public laybangchuyengiaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manhanvien", DbType="Int NOT NULL")]
		public int manhanvien
		{
			get
			{
				return this._manhanvien;
			}
			set
			{
				if ((this._manhanvien != value))
				{
					this._manhanvien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennhanvien", DbType="NVarChar(200)")]
		public string tennhanvien
		{
			get
			{
				return this._tennhanvien;
			}
			set
			{
				if ((this._tennhanvien != value))
				{
					this._tennhanvien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapBacHienTai", DbType="NVarChar(200)")]
		public string CapBacHienTai
		{
			get
			{
				return this._CapBacHienTai;
			}
			set
			{
				if ((this._CapBacHienTai != value))
				{
					this._CapBacHienTai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVuHienTai", DbType="NVarChar(200)")]
		public string ChucVuHienTai
		{
			get
			{
				return this._ChucVuHienTai;
			}
			set
			{
				if ((this._ChucVuHienTai != value))
				{
					this._ChucVuHienTai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghichu", DbType="NVarChar(2000)")]
		public string ghichu
		{
			get
			{
				return this._ghichu;
			}
			set
			{
				if ((this._ghichu != value))
				{
					this._ghichu = value;
				}
			}
		}
	}
	
	public partial class nlay_bangduanResult
	{
		
		private System.Nullable<int> _MaDuAn;
		
		private int _STT;
		
		private string _TenDuAn;
		
		private string _DiaDiem;
		
		private string _DienTich;
		
		private string _NgayBatDau;
		
		private string _NgayKetThuc;
		
		private System.Nullable<double> _GiaTriHopDong;
		
		private System.Nullable<double> _GiaTriThanhQuyetToan;
		
		private string _TenDoiTruong;
		
		private string _TenNguoiLapHoSo;
		
		private string _FileDinhKem;
		
		private string _GhiChu;
		
		public nlay_bangduanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDuAn", DbType="Int")]
		public System.Nullable<int> MaDuAn
		{
			get
			{
				return this._MaDuAn;
			}
			set
			{
				if ((this._MaDuAn != value))
				{
					this._MaDuAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this._STT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDuAn", DbType="NVarChar(200)")]
		public string TenDuAn
		{
			get
			{
				return this._TenDuAn;
			}
			set
			{
				if ((this._TenDuAn != value))
				{
					this._TenDuAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaDiem", DbType="NVarChar(200)")]
		public string DiaDiem
		{
			get
			{
				return this._DiaDiem;
			}
			set
			{
				if ((this._DiaDiem != value))
				{
					this._DiaDiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DienTich", DbType="VarChar(50)")]
		public string DienTich
		{
			get
			{
				return this._DienTich;
			}
			set
			{
				if ((this._DienTich != value))
				{
					this._DienTich = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="VarChar(10)")]
		public string NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this._NgayBatDau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="VarChar(10)")]
		public string NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this._NgayKetThuc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriHopDong", DbType="Float")]
		public System.Nullable<double> GiaTriHopDong
		{
			get
			{
				return this._GiaTriHopDong;
			}
			set
			{
				if ((this._GiaTriHopDong != value))
				{
					this._GiaTriHopDong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaTriThanhQuyetToan", DbType="Float")]
		public System.Nullable<double> GiaTriThanhQuyetToan
		{
			get
			{
				return this._GiaTriThanhQuyetToan;
			}
			set
			{
				if ((this._GiaTriThanhQuyetToan != value))
				{
					this._GiaTriThanhQuyetToan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDoiTruong", DbType="NVarChar(200)")]
		public string TenDoiTruong
		{
			get
			{
				return this._TenDoiTruong;
			}
			set
			{
				if ((this._TenDoiTruong != value))
				{
					this._TenDoiTruong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiLapHoSo", DbType="NVarChar(200)")]
		public string TenNguoiLapHoSo
		{
			get
			{
				return this._TenNguoiLapHoSo;
			}
			set
			{
				if ((this._TenNguoiLapHoSo != value))
				{
					this._TenNguoiLapHoSo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileDinhKem", DbType="NVarChar(2000)")]
		public string FileDinhKem
		{
			get
			{
				return this._FileDinhKem;
			}
			set
			{
				if ((this._FileDinhKem != value))
				{
					this._FileDinhKem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(2000)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this._GhiChu = value;
				}
			}
		}
	}
	
	public partial class ntimkiem_namResult
	{
		
		private System.Nullable<int> _MaDuAn;
		
		private string _NgayBatDau;
		
		private string _NgayKetThuc;
		
		public ntimkiem_namResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDuAn", DbType="Int")]
		public System.Nullable<int> MaDuAn
		{
			get
			{
				return this._MaDuAn;
			}
			set
			{
				if ((this._MaDuAn != value))
				{
					this._MaDuAn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="VarChar(10)")]
		public string NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this._NgayBatDau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="VarChar(10)")]
		public string NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this._NgayKetThuc = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
