<?xml version="1.0" encoding="utf-8"?><Database Name="QUANLYHOSO" Class="LINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-NSHA70OK\SQLEXPRESS01;Initial Catalog=QUANLYHOSO;Integrated Security=True" SettingsObjectName="QLHS.Properties.Settings" SettingsPropertyName="QUANLYHOSOConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenNhanVien" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CapBacHienTai" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ChucVuHienTai" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien_DuAn" Member="NhanVien_DuAns">
    <Type Name="NhanVien_DuAn">
      <Column Name="MaNhanVien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaDuAn" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CapBac" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DuAn" Member="DuAns">
    <Type Name="DuAn">
      <Column Name="MaDuAn" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDuAn" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DiaDiem" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DienTich" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgayBatDau" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgayKetThuc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="GiaTriHopDong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GiaTriThanhQuyetToan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="MaDoiTruong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNguoiLapHoSo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FileDinhKem" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="nlhskhac" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="dttckhac" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.lay_capbac" Method="lay_capbac" IsComposable="true">
    <Parameter Name="manhanvien" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.lay_chucvu" Method="lay_chucvu" IsComposable="true">
    <Parameter Name="manhanvien" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.lay_cottenduan" Method="lay_cottenduan" IsComposable="true">
    <ElementType Name="lay_cottenduanResult">
      <Column Name="tenduan" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.lay_cottennhanvien" Method="lay_cottennhanvien" IsComposable="true">
    <ElementType Name="lay_cottennhanvienResult">
      <Column Name="tennhanvien" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.lay_diadiem" Method="lay_diadiem" IsComposable="true">
    <Parameter Name="maduan" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.lay_dientich" Method="lay_dientich" IsComposable="true">
    <Parameter Name="maduan" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.lay_filedinhkiem" Method="lay_filedinhkiem" IsComposable="true">
    <Parameter Name="maduan" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.lay_giatrihopdong" Method="lay_giatrihopdong" IsComposable="true">
    <Parameter Name="maduan" Type="System.Int32" DbType="Int" />
    <Return Type="System.Double" />
  </Function>
  <Function Name="dbo.lay_giatrithanhquyettoan" Method="lay_giatrithanhquyettoan" IsComposable="true">
    <Parameter Name="maduan" Type="System.Int32" DbType="Int" />
    <Return Type="System.Double" />
  </Function>
  <Function Name="dbo.lay_madoitruong" Method="lay_madoitruong" IsComposable="true">
    <Parameter Name="maduan" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.lay_manguoilaphoso" Method="lay_manguoilaphoso" IsComposable="true">
    <Parameter Name="maduan" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.lay_ngaybatdau" Method="lay_ngaybatdau" IsComposable="true">
    <Parameter Name="maduan" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.lay_ngayketthuc" Method="lay_ngayketthuc" IsComposable="true">
    <Parameter Name="maduan" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.lay_tenduan" Method="lay_tenduan" IsComposable="true">
    <Parameter Name="maduan" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.lay_tennhanvien" Method="lay_tennhanvien" IsComposable="true">
    <Parameter Name="manhanvien" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.lay_trangthai" Method="lay_trangthai" IsComposable="true">
    <Parameter Name="manhanvien" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.lay_idcuoi" Method="lay_idcuoi" IsComposable="true">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.chuyensx" Method="chuyensx" IsComposable="true">
    <ElementType Name="chuyensxResult">
      <Column Name="MaDuAn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayBatDau" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgayKetThuc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.lay_cottenchuyengia" Method="lay_cottenchuyengia" IsComposable="true">
    <ElementType Name="lay_cottenchuyengiaResult">
      <Column Name="tennhanvien" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.nlay_manhanvien" Method="nlay_manhanvien" IsComposable="true">
    <Parameter Name="tennhanvien" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="loai" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.lay_idcuoinhanvien" Method="lay_idcuoinhanvien" IsComposable="true">
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.timkiem_nam" Method="timkiem_nam" IsComposable="true">
    <Parameter Name="nam" Type="System.Int32" DbType="Int" />
    <ElementType Name="timkiem_namResult">
      <Column Name="MaDuAn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenDuAn" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DiaDiem" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DienTich" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgayBatDau" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgayKetThuc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="GiaTriHopDong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GiaTriThanhQuyetToan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TenDoiTruong" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TenNguoiLapHoSo" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="FileDinhKem" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.timkiem_tenduan" Method="timkiem_tenduan" IsComposable="true">
    <Parameter Name="ten" Type="System.String" DbType="NVarChar(200)" />
    <ElementType Name="timkiem_tenduanResult">
      <Column Name="MaDuAn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenDuAn" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DiaDiem" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DienTich" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgayBatDau" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgayKetThuc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="GiaTriHopDong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GiaTriThanhQuyetToan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TenDoiTruong" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TenNguoiLapHoSo" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="FileDinhKem" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.ntimkiemchung" Method="ntimkiemchung" IsComposable="true">
    <Parameter Name="chuoi" Type="System.String" DbType="NVarChar(200)" />
    <ElementType Name="ntimkiemchungResult">
      <Column Name="MaDuAn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenDuAn" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DiaDiem" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DienTich" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgayBatDau" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgayKetThuc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="GiaTriHopDong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GiaTriThanhQuyetToan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TenDoiTruong" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TenNguoiLapHoSo" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="FileDinhKem" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.nthem_nhanvien" Method="nthem_nhanvien">
    <Parameter Name="tennhanvien" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="capbac" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="chucvu" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="trangthai" Type="System.Int32" DbType="Int" />
    <Parameter Name="ghichu" Type="System.String" DbType="NVarChar(2000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.nsua_nhanvien" Method="nsua_nhanvien">
    <Parameter Name="manhanvien" Type="System.Int32" DbType="Int" />
    <Parameter Name="tennhanvien" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="capbac" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="chucvu" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="trangthai" Type="System.Int32" DbType="Int" />
    <Parameter Name="ghichu" Type="System.String" DbType="NVarChar(2000)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.nlay_bangnhanvien" Method="nlay_bangnhanvien" IsComposable="true">
    <ElementType Name="nlay_bangnhanvienResult">
      <Column Name="manhanvien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tennhanvien" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CapBacHienTai" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ChucVuHienTai" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.xoaduan" Method="xoaduan">
    <Parameter Name="maduan" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.xoanhanvien" Method="xoanhanvien">
    <Parameter Name="ma" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.laybangchuyengia" Method="laybangchuyengia" IsComposable="true">
    <ElementType Name="laybangchuyengiaResult">
      <Column Name="manhanvien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tennhanvien" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="CapBacHienTai" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ChucVuHienTai" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ghichu" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.nlay_bangduan" Method="nlay_bangduan" IsComposable="true">
    <ElementType Name="nlay_bangduanResult">
      <Column Name="MaDuAn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenDuAn" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DiaDiem" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="DienTich" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NgayBatDau" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgayKetThuc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="GiaTriHopDong" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="GiaTriThanhQuyetToan" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TenDoiTruong" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TenNguoiLapHoSo" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="FileDinhKem" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.lay_nlhskhac" Method="lay_nlhskhac" IsComposable="true">
    <Parameter Name="maduan" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.lay_dttckhac" Method="lay_dttckhac" IsComposable="true">
    <Parameter Name="maduan" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.lay_ghichuduan" Method="lay_ghichuduan" IsComposable="true">
    <Parameter Name="maduan" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.lay_ghichunhanvien" Method="lay_ghichunhanvien" IsComposable="true">
    <Parameter Name="manhanvien" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.ntimkiem_nam" Method="ntimkiem_nam" IsComposable="true">
    <Parameter Name="nam" Type="System.String" DbType="VarChar(10)" />
    <ElementType Name="ntimkiem_namResult">
      <Column Name="MaDuAn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayBatDau" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="NgayKetThuc" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.lay_manhanvien" Method="lay_manhanvien" IsComposable="true">
    <Parameter Name="tennhanvien" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="capbac" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="chucvu" Type="System.String" DbType="NVarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.nthem_duan" Method="nthem_duan">
    <Parameter Name="tenduan" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="diadiem" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="dientich" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ngaybatdau" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="ngayketthuc" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="gthd" Type="System.Double" DbType="Float" />
    <Parameter Name="gttqt" Type="System.Double" DbType="Float" />
    <Parameter Name="nth" Type="System.Int32" DbType="Int" />
    <Parameter Name="dttc" Type="System.Int32" DbType="Int" />
    <Parameter Name="file" Type="System.String" DbType="NVarChar(2000)" />
    <Parameter Name="ghichu" Type="System.String" DbType="NVarChar(2000)" />
    <Parameter Name="nlhskhac" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="dttckhac" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="gthdchu" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="gttqtchu" Type="System.String" DbType="NVarChar(500)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.nsua_duan" Method="nsua_duan">
    <Parameter Name="maduan" Type="System.Int32" DbType="Int" />
    <Parameter Name="tenduan" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="diadiem" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="dientich" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ngaybatdau" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="ngayketthuc" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="gthd" Type="System.Double" DbType="Float" />
    <Parameter Name="gttqt" Type="System.Double" DbType="Float" />
    <Parameter Name="nth" Type="System.Int32" DbType="Int" />
    <Parameter Name="dttc" Type="System.Int32" DbType="Int" />
    <Parameter Name="file" Type="System.String" DbType="NVarChar(2000)" />
    <Parameter Name="ghichu" Type="System.String" DbType="NVarChar(2000)" />
    <Parameter Name="nlhskhac" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="dttckhac" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="gthdchu" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="gttqtchu" Type="System.String" DbType="NVarChar(500)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.lay_gthdchu" Method="lay_gthdchu" IsComposable="true">
    <Parameter Name="maduan" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.lay_gttqtchu" Method="lay_gttqtchu" IsComposable="true">
    <Parameter Name="maduan" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
</Database>